### ISSUE TITLE
prometheus labels

### ISSUE THREAD

**Issue by suikast42** [suikast42/nomadder#166]
Current approach for having dynmamic labels for prometehus is:

```yaml
            - source_labels: [__meta_consul_tags]
              target_label: 'service_id'
              regex: '.*?prometheus:service_id=([^, ]+).*'
              replacement: '$${1}'
              action: 'replace'
```

Find a way over grafana-agen ( or replace it with allow ) 

Approach 1. is to label prometheus_labels:key1=value1,keyn=valuen
```yaml
   - source_labels: ['__meta_consul_tags']
     regex: '.*prometheus_labels:([^ ]+).*'
     replacement: '$${1}'
     target_label: '__tmp_extracted_labels'
     action: 'replace'
  - source_labels: ['__tmp_extracted_labels']
    regex: '([^=,]+)=([^,]+)'
    replacement: '${2}'
    target_label: '${1}'
    action: 'labelmap'	
```

Approach 2:  find all lables kv pars from __meta_consul_tags and add it to labels
